/*******************************************************
* Author: Abdullah Abdelhakeem
* Date: September 30, 2023
* Description: Handle Interrupt Signal like (ctrl + c) in C++
*
* Type: Task
* Language: C++
* Dependencies: None
* IDE: VS Code
* Compiler: G++
* OS: Windows 10
*
* Inputs:
* Outputs:
*
* Algorithm:
*   1.
*
* Note:
*        Signals (Software Interrupts in User Space):
*        SIGINT: Interrupt signal, usually generated by pressing Ctrl+C in the terminal.
*        SIGILL: Illegal instruction signal.
*        SIGSEGV: Segmentation violation signal.
*        SIGFPE: Floating-point exception signal.
*        SIGABRT: Abort signal.
*******************************************************/
#include<iostream>
#include<csignal>
void signalHandler(int signum)
{
    std::cout << "Interrupt signal "<<signum << "Received" << std::endl;
    exit(signum);
}
int main(){
    signal(SIGINT, signalHandler);
    // signal(SIGTERM, signalHandler); // Termination signal

    std::cout << "Press Ctrl+C to trigger the interrupt signal." << std::endl;

    while (true) {

    }

    return 0;
}